# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: githab_actions

on: push

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
     - uses: actions/checkout@v2
     - name: npm install
       run: make install
     - name: Run linter
       run: make lint
       env:
        CI: true

       
       
     
